###############################################################
#  Generated by:      Cadence Innovus 17.12-s095_1
#  OS:                Linux x86_64(Host ID cadence1)
#  Generated on:      Wed Dec 20 13:01:31 2023
#  Design:            fifo_mem
#  Command:           saveDesign top_post_route_and_filler
###############################################################
current_design fifo_mem
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_wire_load_mode enclosed
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/adiode}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/slbhb1}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/cload1}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/slbhb4}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/bh01d1}]
set_dont_use  [get_lib_cells {tsl18fs120_scl_ss/slbhb2}]
