
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Dec 20 2023 12:50:36 IST (Dec 20 2023 07:20:36 UTC)

// Verification Directory fv/fifo_mem 

module fifo_mem(data_out, fifo_full, fifo_empty, fifo_threshold,
     fifo_overflow, fifo_underflow, clk, rst_n, wr, rd, data_in);
  input clk, rst_n, wr, rd;
  input [7:0] data_in;
  output [7:0] data_out;
  output fifo_full, fifo_empty, fifo_threshold, fifo_overflow,
       fifo_underflow;
  wire clk, rst_n, wr, rd;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire fifo_full, fifo_empty, fifo_threshold, fifo_overflow,
       fifo_underflow;
  wire [7:0] \top3_data_out2[15] ;
  wire [7:0] \top3_data_out2[7] ;
  wire [7:0] \top3_data_out2[0] ;
  wire [4:0] wptr;
  wire [7:0] \top3_data_out2[13] ;
  wire [7:0] \top3_data_out2[10] ;
  wire [7:0] \top3_data_out2[11] ;
  wire [7:0] \top3_data_out2[4] ;
  wire [7:0] \top3_data_out2[9] ;
  wire [7:0] \top3_data_out2[1] ;
  wire [7:0] \top3_data_out2[14] ;
  wire [7:0] \top3_data_out2[2] ;
  wire [7:0] \top3_data_out2[12] ;
  wire [7:0] \top3_data_out2[5] ;
  wire [7:0] \top3_data_out2[8] ;
  wire [7:0] \top3_data_out2[6] ;
  wire [7:0] \top3_data_out2[3] ;
  wire [4:0] rptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_133, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_255, n_256;
  wire n_257, n_258, n_259, n_260, n_261, n_262, n_263, n_264;
  wire n_265, n_266, n_267, n_268, n_269, n_270, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_292, n_293, n_294, n_295, n_296, n_297, n_298;
  wire n_299, n_300, n_301, n_302, n_303, n_304, n_305, n_306;
  wire n_307, n_308, n_309, n_310, n_311, n_312, n_313, n_314;
  wire n_315, n_316, n_317, n_318, n_319, n_320, n_321, n_322;
  wire n_327, n_328, n_329;
  dfnrq1 \top3_data_out2_reg[15][3] (.CP (clk), .D (n_315), .Q
       (\top3_data_out2[15] [3]));
  dfnrq1 \top3_data_out2_reg[15][0] (.CP (clk), .D (n_320), .Q
       (\top3_data_out2[15] [0]));
  dfnrq1 \top3_data_out2_reg[15][1] (.CP (clk), .D (n_317), .Q
       (\top3_data_out2[15] [1]));
  dfnrq1 \top3_data_out2_reg[15][4] (.CP (clk), .D (n_316), .Q
       (\top3_data_out2[15] [4]));
  dfnrq1 \top3_data_out2_reg[15][7] (.CP (clk), .D (n_318), .Q
       (\top3_data_out2[15] [7]));
  dfnrq1 \top3_data_out2_reg[15][6] (.CP (clk), .D (n_321), .Q
       (\top3_data_out2[15] [6]));
  dfnrq1 \top3_data_out2_reg[15][5] (.CP (clk), .D (n_312), .Q
       (\top3_data_out2[15] [5]));
  dfnrq1 \top3_data_out2_reg[15][2] (.CP (clk), .D (n_314), .Q
       (\top3_data_out2[15] [2]));
  dfnrq1 \top3_data_out2_reg[7][1] (.CP (clk), .D (n_310), .Q
       (\top3_data_out2[7] [1]));
  dfnrq1 \top3_data_out2_reg[7][0] (.CP (clk), .D (n_306), .Q
       (\top3_data_out2[7] [0]));
  dfnrq1 \top3_data_out2_reg[7][7] (.CP (clk), .D (n_303), .Q
       (\top3_data_out2[7] [7]));
  dfnrq1 \top3_data_out2_reg[7][3] (.CP (clk), .D (n_307), .Q
       (\top3_data_out2[7] [3]));
  oai21d1 g7089__8780(.A (n_277), .B1 (n_6), .B2 (n_297), .ZN (n_322));
  dfnrq1 \top3_data_out2_reg[7][5] (.CP (clk), .D (n_305), .Q
       (\top3_data_out2[7] [5]));
  dfnrq1 \top3_data_out2_reg[7][4] (.CP (clk), .D (n_311), .Q
       (\top3_data_out2[7] [4]));
  dfnrq1 \top3_data_out2_reg[7][6] (.CP (clk), .D (n_304), .Q
       (\top3_data_out2[7] [6]));
  dfnrq1 \top3_data_out2_reg[7][2] (.CP (clk), .D (n_308), .Q
       (\top3_data_out2[7] [2]));
  mx02d1 g7084__4296(.I0 (data_in[6]), .I1 (\top3_data_out2[15] [6]),
       .S (n_319), .Z (n_321));
  mx02d1 g7086__3772(.I0 (data_in[0]), .I1 (\top3_data_out2[15] [0]),
       .S (n_319), .Z (n_320));
  mx02d1 g7085__1474(.I0 (data_in[7]), .I1 (\top3_data_out2[15] [7]),
       .S (n_319), .Z (n_318));
  mx02d1 g7087__4547(.I0 (data_in[1]), .I1 (\top3_data_out2[15] [1]),
       .S (n_319), .Z (n_317));
  dfnrq1 \top3_data_out2_reg[0][3] (.CP (clk), .D (n_290), .Q
       (\top3_data_out2[0] [3]));
  dfnrq1 \top3_data_out2_reg[0][4] (.CP (clk), .D (n_288), .Q
       (\top3_data_out2[0] [4]));
  dfnrq1 \top3_data_out2_reg[0][2] (.CP (clk), .D (n_292), .Q
       (\top3_data_out2[0] [2]));
  dfnrq1 \top3_data_out2_reg[0][6] (.CP (clk), .D (n_286), .Q
       (\top3_data_out2[0] [6]));
  dfnrq1 \top3_data_out2_reg[0][7] (.CP (clk), .D (n_285), .Q
       (\top3_data_out2[0] [7]));
  dfnrq1 \top3_data_out2_reg[0][1] (.CP (clk), .D (n_289), .Q
       (\top3_data_out2[0] [1]));
  dfnrq1 \top3_data_out2_reg[0][5] (.CP (clk), .D (n_287), .Q
       (\top3_data_out2[0] [5]));
  dfnrq1 \top3_data_out2_reg[0][0] (.CP (clk), .D (n_293), .Q
       (\top3_data_out2[0] [0]));
  mx02d1 g7082__9682(.I0 (data_in[4]), .I1 (\top3_data_out2[15] [4]),
       .S (n_319), .Z (n_316));
  mx02d1 g7080__2683(.I0 (data_in[3]), .I1 (\top3_data_out2[15] [3]),
       .S (n_319), .Z (n_315));
  mx02d1 g7088__1309(.I0 (data_in[2]), .I1 (\top3_data_out2[15] [2]),
       .S (n_319), .Z (n_314));
  oaim22d1 g7081__6877(.A1 (wptr[4]), .A2 (n_319), .B1 (wptr[4]), .B2
       (n_319), .ZN (n_313));
  mx02d1 g7083__2900(.I0 (data_in[5]), .I1 (\top3_data_out2[15] [5]),
       .S (n_319), .Z (n_312));
  dfnrq1 \top3_data_out2_reg[13][6] (.CP (clk), .D (n_294), .Q
       (\top3_data_out2[13] [6]));
  dfnrq1 \top3_data_out2_reg[13][3] (.CP (clk), .D (n_302), .Q
       (\top3_data_out2[13] [3]));
  dfnrq1 \top3_data_out2_reg[13][7] (.CP (clk), .D (n_284), .Q
       (\top3_data_out2[13] [7]));
  dfnrq1 \top3_data_out2_reg[13][0] (.CP (clk), .D (n_301), .Q
       (\top3_data_out2[13] [0]));
  dfnrq1 \top3_data_out2_reg[13][1] (.CP (clk), .D (n_299), .Q
       (\top3_data_out2[13] [1]));
  dfnrq1 \top3_data_out2_reg[13][2] (.CP (clk), .D (n_298), .Q
       (\top3_data_out2[13] [2]));
  dfnrq1 \top3_data_out2_reg[13][4] (.CP (clk), .D (n_296), .Q
       (\top3_data_out2[13] [4]));
  dfnrq1 \top3_data_out2_reg[13][5] (.CP (clk), .D (n_295), .Q
       (\top3_data_out2[13] [5]));
  dfnrq1 \top3_data_out2_reg[10][4] (.CP (clk), .D (n_221), .Q
       (\top3_data_out2[10] [4]));
  dfnrq1 \top3_data_out2_reg[11][0] (.CP (clk), .D (n_238), .Q
       (\top3_data_out2[11] [0]));
  dfnrq1 \top3_data_out2_reg[10][0] (.CP (clk), .D (n_226), .Q
       (\top3_data_out2[10] [0]));
  dfnrq1 \top3_data_out2_reg[4][6] (.CP (clk), .D (n_254), .Q
       (\top3_data_out2[4] [6]));
  dfnrq1 \top3_data_out2_reg[9][4] (.CP (clk), .D (n_283), .Q
       (\top3_data_out2[9] [4]));
  dfnrq1 \top3_data_out2_reg[1][0] (.CP (clk), .D (n_217), .Q
       (\top3_data_out2[1] [0]));
  dfnrq1 \top3_data_out2_reg[1][1] (.CP (clk), .D (n_216), .Q
       (\top3_data_out2[1] [1]));
  dfnrq1 \top3_data_out2_reg[1][2] (.CP (clk), .D (n_214), .Q
       (\top3_data_out2[1] [2]));
  dfnrq1 \top3_data_out2_reg[1][3] (.CP (clk), .D (n_213), .Q
       (\top3_data_out2[1] [3]));
  dfnrq1 \top3_data_out2_reg[1][4] (.CP (clk), .D (n_212), .Q
       (\top3_data_out2[1] [4]));
  dfnrq1 \top3_data_out2_reg[1][5] (.CP (clk), .D (n_211), .Q
       (\top3_data_out2[1] [5]));
  dfnrq1 \top3_data_out2_reg[1][6] (.CP (clk), .D (n_210), .Q
       (\top3_data_out2[1] [6]));
  dfnrq1 \top3_data_out2_reg[14][6] (.CP (clk), .D (n_230), .Q
       (\top3_data_out2[14] [6]));
  dfnrq1 \top3_data_out2_reg[1][7] (.CP (clk), .D (n_209), .Q
       (\top3_data_out2[1] [7]));
  dfnrq1 \top3_data_out2_reg[2][0] (.CP (clk), .D (n_198), .Q
       (\top3_data_out2[2] [0]));
  dfnrq1 \top3_data_out2_reg[2][1] (.CP (clk), .D (n_202), .Q
       (\top3_data_out2[2] [1]));
  dfnrq1 \top3_data_out2_reg[2][2] (.CP (clk), .D (n_195), .Q
       (\top3_data_out2[2] [2]));
  dfnrq1 \top3_data_out2_reg[2][3] (.CP (clk), .D (n_191), .Q
       (\top3_data_out2[2] [3]));
  dfnrq1 \top3_data_out2_reg[2][4] (.CP (clk), .D (n_188), .Q
       (\top3_data_out2[2] [4]));
  dfnrq1 \top3_data_out2_reg[2][5] (.CP (clk), .D (n_185), .Q
       (\top3_data_out2[2] [5]));
  dfnrq1 \top3_data_out2_reg[2][6] (.CP (clk), .D (n_182), .Q
       (\top3_data_out2[2] [6]));
  dfnrq1 \top3_data_out2_reg[2][7] (.CP (clk), .D (n_179), .Q
       (\top3_data_out2[2] [7]));
  dfnrq1 \top3_data_out2_reg[4][1] (.CP (clk), .D (n_270), .Q
       (\top3_data_out2[4] [1]));
  dfnrq1 \top3_data_out2_reg[4][2] (.CP (clk), .D (n_269), .Q
       (\top3_data_out2[4] [2]));
  dfnrq1 \top3_data_out2_reg[4][3] (.CP (clk), .D (n_264), .Q
       (\top3_data_out2[4] [3]));
  dfnrq1 \top3_data_out2_reg[4][4] (.CP (clk), .D (n_261), .Q
       (\top3_data_out2[4] [4]));
  dfnrq1 \top3_data_out2_reg[4][5] (.CP (clk), .D (n_257), .Q
       (\top3_data_out2[4] [5]));
  dfnrq1 \top3_data_out2_reg[12][4] (.CP (clk), .D (n_189), .Q
       (\top3_data_out2[12] [4]));
  dfnrq1 \top3_data_out2_reg[4][7] (.CP (clk), .D (n_251), .Q
       (\top3_data_out2[4] [7]));
  dfnrq1 \top3_data_out2_reg[5][0] (.CP (clk), .D (n_247), .Q
       (\top3_data_out2[5] [0]));
  dfnrq1 \top3_data_out2_reg[5][1] (.CP (clk), .D (n_244), .Q
       (\top3_data_out2[5] [1]));
  dfnrq1 \top3_data_out2_reg[5][2] (.CP (clk), .D (n_240), .Q
       (\top3_data_out2[5] [2]));
  dfnrq1 \top3_data_out2_reg[5][3] (.CP (clk), .D (n_237), .Q
       (\top3_data_out2[5] [3]));
  dfnrq1 \top3_data_out2_reg[5][5] (.CP (clk), .D (n_235), .Q
       (\top3_data_out2[5] [5]));
  dfnrq1 \top3_data_out2_reg[8][1] (.CP (clk), .D (n_282), .Q
       (\top3_data_out2[8] [1]));
  dfnrq1 \top3_data_out2_reg[5][7] (.CP (clk), .D (n_234), .Q
       (\top3_data_out2[5] [7]));
  dfnrq1 \top3_data_out2_reg[6][0] (.CP (clk), .D (n_208), .Q
       (\top3_data_out2[6] [0]));
  dfnrq1 \top3_data_out2_reg[6][1] (.CP (clk), .D (n_207), .Q
       (\top3_data_out2[6] [1]));
  dfnrq1 \top3_data_out2_reg[6][2] (.CP (clk), .D (n_205), .Q
       (\top3_data_out2[6] [2]));
  dfnrq1 \top3_data_out2_reg[6][3] (.CP (clk), .D (n_204), .Q
       (\top3_data_out2[6] [3]));
  dfnrq1 \top3_data_out2_reg[6][4] (.CP (clk), .D (n_203), .Q
       (\top3_data_out2[6] [4]));
  dfnrq1 \top3_data_out2_reg[5][4] (.CP (clk), .D (n_236), .Q
       (\top3_data_out2[5] [4]));
  dfnrq1 \top3_data_out2_reg[6][6] (.CP (clk), .D (n_200), .Q
       (\top3_data_out2[6] [6]));
  dfnrq1 \top3_data_out2_reg[6][7] (.CP (clk), .D (n_199), .Q
       (\top3_data_out2[6] [7]));
  dfnrq1 \top3_data_out2_reg[5][6] (.CP (clk), .D (n_232), .Q
       (\top3_data_out2[5] [6]));
  dfnrq1 \top3_data_out2_reg[6][5] (.CP (clk), .D (n_201), .Q
       (\top3_data_out2[6] [5]));
  dfnrq1 \top3_data_out2_reg[4][0] (.CP (clk), .D (n_265), .Q
       (\top3_data_out2[4] [0]));
  dfnrq1 \top3_data_out2_reg[8][0] (.CP (clk), .D (n_176), .Q
       (\top3_data_out2[8] [0]));
  dfnrq1 \top3_data_out2_reg[8][3] (.CP (clk), .D (n_279), .Q
       (\top3_data_out2[8] [3]));
  dfnrq1 \top3_data_out2_reg[8][4] (.CP (clk), .D (n_278), .Q
       (\top3_data_out2[8] [4]));
  dfnrq1 \top3_data_out2_reg[8][5] (.CP (clk), .D (n_276), .Q
       (\top3_data_out2[8] [5]));
  dfnrq1 \top3_data_out2_reg[8][6] (.CP (clk), .D (n_275), .Q
       (\top3_data_out2[8] [6]));
  mx02d1 g7094__2391(.I0 (\top3_data_out2[7] [4]), .I1 (data_in[4]), .S
       (n_309), .Z (n_311));
  mx02d1 g7091__7675(.I0 (\top3_data_out2[7] [1]), .I1 (data_in[1]), .S
       (n_309), .Z (n_310));
  mx02d1 g7092__7118(.I0 (\top3_data_out2[7] [2]), .I1 (data_in[2]), .S
       (n_309), .Z (n_308));
  mx02d1 g7093__8757(.I0 (\top3_data_out2[7] [3]), .I1 (data_in[3]), .S
       (n_309), .Z (n_307));
  mx02d1 g7090__1786(.I0 (\top3_data_out2[7] [0]), .I1 (data_in[0]), .S
       (n_309), .Z (n_306));
  mx02d1 g7095__5953(.I0 (\top3_data_out2[7] [5]), .I1 (data_in[5]), .S
       (n_309), .Z (n_305));
  mx02d1 g7096__5703(.I0 (\top3_data_out2[7] [6]), .I1 (data_in[6]), .S
       (n_309), .Z (n_304));
  mx02d1 g7097__7114(.I0 (\top3_data_out2[7] [7]), .I1 (data_in[7]), .S
       (n_309), .Z (n_303));
  dfnrq1 \top3_data_out2_reg[14][0] (.CP (clk), .D (n_183), .Q
       (\top3_data_out2[14] [0]));
  dfnrq1 \top3_data_out2_reg[14][1] (.CP (clk), .D (n_181), .Q
       (\top3_data_out2[14] [1]));
  dfnrq1 \top3_data_out2_reg[14][2] (.CP (clk), .D (n_180), .Q
       (\top3_data_out2[14] [2]));
  dfnrq1 \top3_data_out2_reg[14][4] (.CP (clk), .D (n_177), .Q
       (\top3_data_out2[14] [4]));
  dfnrq1 \top3_data_out2_reg[14][5] (.CP (clk), .D (n_175), .Q
       (\top3_data_out2[14] [5]));
  dfnrq1 \top3_data_out2_reg[12][0] (.CP (clk), .D (n_192), .Q
       (\top3_data_out2[12] [0]));
  dfnrq1 \top3_data_out2_reg[14][7] (.CP (clk), .D (n_273), .Q
       (\top3_data_out2[14] [7]));
  dfnrq1 \top3_data_out2_reg[14][3] (.CP (clk), .D (n_178), .Q
       (\top3_data_out2[14] [3]));
  dfnrq1 \top3_data_out2_reg[9][2] (.CP (clk), .D (n_267), .Q
       (\top3_data_out2[9] [2]));
  dfnrq1 \top3_data_out2_reg[9][3] (.CP (clk), .D (n_272), .Q
       (\top3_data_out2[9] [3]));
  dfnrq1 \top3_data_out2_reg[9][5] (.CP (clk), .D (n_228), .Q
       (\top3_data_out2[9] [5]));
  dfnrq1 \top3_data_out2_reg[9][6] (.CP (clk), .D (n_174), .Q
       (\top3_data_out2[9] [6]));
  dfnrq1 \top3_data_out2_reg[9][7] (.CP (clk), .D (n_227), .Q
       (\top3_data_out2[9] [7]));
  dfnrq1 \top3_data_out2_reg[10][1] (.CP (clk), .D (n_223), .Q
       (\top3_data_out2[10] [1]));
  dfnrq1 \top3_data_out2_reg[10][2] (.CP (clk), .D (n_225), .Q
       (\top3_data_out2[10] [2]));
  dfnrq1 \top3_data_out2_reg[10][3] (.CP (clk), .D (n_222), .Q
       (\top3_data_out2[10] [3]));
  dfnrq1 \top3_data_out2_reg[10][5] (.CP (clk), .D (n_220), .Q
       (\top3_data_out2[10] [5]));
  dfnrq1 \top3_data_out2_reg[10][6] (.CP (clk), .D (n_219), .Q
       (\top3_data_out2[10] [6]));
  dfnrq1 \top3_data_out2_reg[8][7] (.CP (clk), .D (n_274), .Q
       (\top3_data_out2[8] [7]));
  dfnrq1 \top3_data_out2_reg[12][2] (.CP (clk), .D (n_194), .Q
       (\top3_data_out2[12] [2]));
  dfnrq1 \top3_data_out2_reg[12][3] (.CP (clk), .D (n_190), .Q
       (\top3_data_out2[12] [3]));
  dfnrq1 \top3_data_out2_reg[3][7] (.CP (clk), .D (n_263), .Q
       (\top3_data_out2[3] [7]));
  dfnrq1 \top3_data_out2_reg[3][1] (.CP (clk), .D (n_248), .Q
       (\top3_data_out2[3] [1]));
  dfnrq1 \top3_data_out2_reg[3][2] (.CP (clk), .D (n_246), .Q
       (\top3_data_out2[3] [2]));
  dfnrq1 \top3_data_out2_reg[3][3] (.CP (clk), .D (n_245), .Q
       (\top3_data_out2[3] [3]));
  dfnrq1 \top3_data_out2_reg[3][4] (.CP (clk), .D (n_242), .Q
       (\top3_data_out2[3] [4]));
  dfnrq1 \top3_data_out2_reg[3][5] (.CP (clk), .D (n_241), .Q
       (\top3_data_out2[3] [5]));
  dfnrq1 \top3_data_out2_reg[3][6] (.CP (clk), .D (n_239), .Q
       (\top3_data_out2[3] [6]));
  dfnrq1 \top3_data_out2_reg[12][1] (.CP (clk), .D (n_196), .Q
       (\top3_data_out2[12] [1]));
  dfnrq1 \top3_data_out2_reg[11][1] (.CP (clk), .D (n_262), .Q
       (\top3_data_out2[11] [1]));
  dfnrq1 \top3_data_out2_reg[11][2] (.CP (clk), .D (n_260), .Q
       (\top3_data_out2[11] [2]));
  dfnrq1 \top3_data_out2_reg[11][3] (.CP (clk), .D (n_258), .Q
       (\top3_data_out2[11] [3]));
  dfnrq1 \top3_data_out2_reg[11][6] (.CP (clk), .D (n_253), .Q
       (\top3_data_out2[11] [6]));
  dfnrq1 \top3_data_out2_reg[11][7] (.CP (clk), .D (n_252), .Q
       (\top3_data_out2[11] [7]));
  dfnrq1 \top3_data_out2_reg[11][4] (.CP (clk), .D (n_256), .Q
       (\top3_data_out2[11] [4]));
  dfnrq1 \top3_data_out2_reg[10][7] (.CP (clk), .D (n_218), .Q
       (\top3_data_out2[10] [7]));
  dfnrq1 \top3_data_out2_reg[9][0] (.CP (clk), .D (n_231), .Q
       (\top3_data_out2[9] [0]));
  dfnrq1 \top3_data_out2_reg[12][5] (.CP (clk), .D (n_187), .Q
       (\top3_data_out2[12] [5]));
  dfnrq1 \top3_data_out2_reg[12][6] (.CP (clk), .D (n_186), .Q
       (\top3_data_out2[12] [6]));
  dfnrq1 \top3_data_out2_reg[12][7] (.CP (clk), .D (n_184), .Q
       (\top3_data_out2[12] [7]));
  dfnrq1 \top3_data_out2_reg[8][2] (.CP (clk), .D (n_281), .Q
       (\top3_data_out2[8] [2]));
  dfnrq1 \top3_data_out2_reg[11][5] (.CP (clk), .D (n_255), .Q
       (\top3_data_out2[11] [5]));
  dfnrq1 \top3_data_out2_reg[9][1] (.CP (clk), .D (n_266), .Q
       (\top3_data_out2[9] [1]));
  dfnrq1 \top3_data_out2_reg[3][0] (.CP (clk), .D (n_250), .Q
       (\top3_data_out2[3] [0]));
  mx02d1 g7172__5266(.I0 (\top3_data_out2[13] [3]), .I1 (data_in[3]),
       .S (n_300), .Z (n_302));
  mx02d1 g7169__2250(.I0 (\top3_data_out2[13] [0]), .I1 (data_in[0]),
       .S (n_300), .Z (n_301));
  mx02d1 g7170__6083(.I0 (\top3_data_out2[13] [1]), .I1 (data_in[1]),
       .S (n_300), .Z (n_299));
  mx02d1 g7171__2703(.I0 (\top3_data_out2[13] [2]), .I1 (data_in[2]),
       .S (n_300), .Z (n_298));
  inv0d0 g7243(.I (n_319), .ZN (n_297));
  mx02d1 g7173__5795(.I0 (\top3_data_out2[13] [4]), .I1 (data_in[4]),
       .S (n_300), .Z (n_296));
  mx02d1 g7174__7344(.I0 (\top3_data_out2[13] [5]), .I1 (data_in[5]),
       .S (n_300), .Z (n_295));
  mx02d1 g7175__1840(.I0 (\top3_data_out2[13] [6]), .I1 (data_in[6]),
       .S (n_300), .Z (n_294));
  mx02d1 g7192__5019(.I0 (data_in[0]), .I1 (\top3_data_out2[0] [0]), .S
       (n_327), .Z (n_293));
  mx02d1 g7185__1857(.I0 (data_in[2]), .I1 (\top3_data_out2[0] [2]), .S
       (n_327), .Z (n_292));
  mx02d1 g7186__9906(.I0 (data_in[3]), .I1 (\top3_data_out2[0] [3]), .S
       (n_327), .Z (n_290));
  mx02d1 g7187__8780(.I0 (data_in[1]), .I1 (\top3_data_out2[0] [1]), .S
       (n_327), .Z (n_289));
  mx02d1 g7188__4296(.I0 (data_in[4]), .I1 (\top3_data_out2[0] [4]), .S
       (n_327), .Z (n_288));
  mx02d1 g7189__3772(.I0 (data_in[5]), .I1 (\top3_data_out2[0] [5]), .S
       (n_327), .Z (n_287));
  mx02d1 g7190__1474(.I0 (data_in[6]), .I1 (\top3_data_out2[0] [6]), .S
       (n_327), .Z (n_286));
  mx02d1 g7191__4547(.I0 (data_in[7]), .I1 (\top3_data_out2[0] [7]), .S
       (n_327), .Z (n_285));
  mx02d1 g7176__9682(.I0 (\top3_data_out2[13] [7]), .I1 (data_in[7]),
       .S (n_300), .Z (n_284));
  mx02d1 g7181__2683(.I0 (data_in[4]), .I1 (\top3_data_out2[9] [4]), .S
       (n_329), .Z (n_283));
  mx02d1 g7146__1309(.I0 (\top3_data_out2[8] [1]), .I1 (data_in[1]), .S
       (n_280), .Z (n_282));
  mx02d1 g7147__6877(.I0 (\top3_data_out2[8] [2]), .I1 (data_in[2]), .S
       (n_280), .Z (n_281));
  mx02d1 g7148__2900(.I0 (\top3_data_out2[8] [3]), .I1 (data_in[3]), .S
       (n_280), .Z (n_279));
  mx02d1 g7149__2391(.I0 (\top3_data_out2[8] [4]), .I1 (data_in[4]), .S
       (n_280), .Z (n_278));
  inv0d0 g7242(.I (n_309), .ZN (n_277));
  mx02d1 g7150__7675(.I0 (\top3_data_out2[8] [5]), .I1 (data_in[5]), .S
       (n_280), .Z (n_276));
  mx02d1 g7151__7118(.I0 (\top3_data_out2[8] [6]), .I1 (data_in[6]), .S
       (n_280), .Z (n_275));
  mx02d1 g7152__8757(.I0 (\top3_data_out2[8] [7]), .I1 (data_in[7]), .S
       (n_280), .Z (n_274));
  mx02d1 g7232__1786(.I0 (\top3_data_out2[14] [7]), .I1 (data_in[7]),
       .S (n_229), .Z (n_273));
  mx02d1 g7180__5953(.I0 (data_in[3]), .I1 (\top3_data_out2[9] [3]), .S
       (n_329), .Z (n_272));
  mx02d1 g7153__5703(.I0 (\top3_data_out2[4] [1]), .I1 (data_in[1]), .S
       (n_268), .Z (n_270));
  mx02d1 g7154__7114(.I0 (\top3_data_out2[4] [2]), .I1 (data_in[2]), .S
       (n_268), .Z (n_269));
  mx02d1 g7179__5266(.I0 (data_in[2]), .I1 (\top3_data_out2[9] [2]), .S
       (n_329), .Z (n_267));
  mx02d1 g7178__2250(.I0 (data_in[1]), .I1 (\top3_data_out2[9] [1]), .S
       (n_329), .Z (n_266));
  mx02d1 g7155__6083(.I0 (\top3_data_out2[4] [0]), .I1 (data_in[0]), .S
       (n_268), .Z (n_265));
  mx02d1 g7156__2703(.I0 (\top3_data_out2[4] [3]), .I1 (data_in[3]), .S
       (n_268), .Z (n_264));
  mx02d1 g7270__5795(.I0 (data_in[7]), .I1 (\top3_data_out2[3] [7]), .S
       (n_249), .Z (n_263));
  mx02d1 g7271__7344(.I0 (\top3_data_out2[11] [1]), .I1 (data_in[1]),
       .S (n_259), .Z (n_262));
  mx02d1 g7157__1840(.I0 (\top3_data_out2[4] [4]), .I1 (data_in[4]), .S
       (n_268), .Z (n_261));
  mx02d1 g7272__5019(.I0 (\top3_data_out2[11] [2]), .I1 (data_in[2]),
       .S (n_259), .Z (n_260));
  mx02d1 g7273__1857(.I0 (\top3_data_out2[11] [3]), .I1 (data_in[3]),
       .S (n_259), .Z (n_258));
  mx02d1 g7158__9906(.I0 (\top3_data_out2[4] [5]), .I1 (data_in[5]), .S
       (n_268), .Z (n_257));
  mx02d1 g7274__8780(.I0 (\top3_data_out2[11] [4]), .I1 (data_in[4]),
       .S (n_259), .Z (n_256));
  mx02d1 g7275__4296(.I0 (\top3_data_out2[11] [5]), .I1 (data_in[5]),
       .S (n_259), .Z (n_255));
  mx02d1 g7159__3772(.I0 (\top3_data_out2[4] [6]), .I1 (data_in[6]), .S
       (n_268), .Z (n_254));
  mx02d1 g7276__1474(.I0 (\top3_data_out2[11] [6]), .I1 (data_in[6]),
       .S (n_259), .Z (n_253));
  mx02d1 g7277__4547(.I0 (\top3_data_out2[11] [7]), .I1 (data_in[7]),
       .S (n_259), .Z (n_252));
  mx02d1 g7160__9682(.I0 (\top3_data_out2[4] [7]), .I1 (data_in[7]), .S
       (n_268), .Z (n_251));
  mx02d1 g7278__2683(.I0 (data_in[0]), .I1 (\top3_data_out2[3] [0]), .S
       (n_249), .Z (n_250));
  mx02d1 g7279__1309(.I0 (data_in[1]), .I1 (\top3_data_out2[3] [1]), .S
       (n_249), .Z (n_248));
  mx02d1 g7161__6877(.I0 (data_in[0]), .I1 (\top3_data_out2[5] [0]), .S
       (n_328), .Z (n_247));
  mx02d1 g7280__2900(.I0 (data_in[2]), .I1 (\top3_data_out2[3] [2]), .S
       (n_249), .Z (n_246));
  mx02d1 g7281__2391(.I0 (data_in[3]), .I1 (\top3_data_out2[3] [3]), .S
       (n_249), .Z (n_245));
  mx02d1 g7162__7675(.I0 (data_in[1]), .I1 (\top3_data_out2[5] [1]), .S
       (n_328), .Z (n_244));
  mx02d1 g7282__7118(.I0 (data_in[4]), .I1 (\top3_data_out2[3] [4]), .S
       (n_249), .Z (n_242));
  mx02d1 g7283__8757(.I0 (data_in[5]), .I1 (\top3_data_out2[3] [5]), .S
       (n_249), .Z (n_241));
  mx02d1 g7163__1786(.I0 (data_in[2]), .I1 (\top3_data_out2[5] [2]), .S
       (n_328), .Z (n_240));
  mx02d1 g7284__5953(.I0 (data_in[6]), .I1 (\top3_data_out2[3] [6]), .S
       (n_249), .Z (n_239));
  mx02d1 g7285__5703(.I0 (\top3_data_out2[11] [0]), .I1 (data_in[0]),
       .S (n_259), .Z (n_238));
  mx02d1 g7164__7114(.I0 (data_in[3]), .I1 (\top3_data_out2[5] [3]), .S
       (n_328), .Z (n_237));
  mx02d1 g7165__5266(.I0 (data_in[4]), .I1 (\top3_data_out2[5] [4]), .S
       (n_328), .Z (n_236));
  mx02d1 g7166__2250(.I0 (data_in[5]), .I1 (\top3_data_out2[5] [5]), .S
       (n_328), .Z (n_235));
  mx02d1 g7167__6083(.I0 (data_in[7]), .I1 (\top3_data_out2[5] [7]), .S
       (n_328), .Z (n_234));
  aoi21d1 g7295__2703(.A (n_167), .B1 (n_2), .B2 (n_163), .ZN (n_233));
  mx02d1 g7168__5795(.I0 (data_in[6]), .I1 (\top3_data_out2[5] [6]), .S
       (n_328), .Z (n_232));
  mx02d1 g7177__7344(.I0 (data_in[0]), .I1 (\top3_data_out2[9] [0]), .S
       (n_329), .Z (n_231));
  dfcrq1 \top2_rptr_reg[4] (.CDN (rst_n), .CP (clk), .D (n_171), .Q
       (rptr[4]));
  nd02d1 g7253__1840(.A1 (wptr[3]), .A2 (n_167), .ZN (n_319));
  mx02d1 g7231__5019(.I0 (\top3_data_out2[14] [6]), .I1 (data_in[6]),
       .S (n_229), .Z (n_230));
  mx02d1 g7183__1857(.I0 (data_in[5]), .I1 (\top3_data_out2[9] [5]), .S
       (n_329), .Z (n_228));
  mx02d1 g7184__9906(.I0 (data_in[7]), .I1 (\top3_data_out2[9] [7]), .S
       (n_329), .Z (n_227));
  mx02d1 g7193__8780(.I0 (\top3_data_out2[10] [0]), .I1 (data_in[0]),
       .S (n_224), .Z (n_226));
  mx02d1 g7195__4296(.I0 (\top3_data_out2[10] [2]), .I1 (data_in[2]),
       .S (n_224), .Z (n_225));
  mx02d1 g7194__3772(.I0 (\top3_data_out2[10] [1]), .I1 (data_in[1]),
       .S (n_224), .Z (n_223));
  mx02d1 g7196__1474(.I0 (\top3_data_out2[10] [3]), .I1 (data_in[3]),
       .S (n_224), .Z (n_222));
  mx02d1 g7197__4547(.I0 (\top3_data_out2[10] [4]), .I1 (data_in[4]),
       .S (n_224), .Z (n_221));
  mx02d1 g7198__9682(.I0 (\top3_data_out2[10] [5]), .I1 (data_in[5]),
       .S (n_224), .Z (n_220));
  mx02d1 g7199__2683(.I0 (\top3_data_out2[10] [6]), .I1 (data_in[6]),
       .S (n_224), .Z (n_219));
  mx02d1 g7200__1309(.I0 (\top3_data_out2[10] [7]), .I1 (data_in[7]),
       .S (n_224), .Z (n_218));
  mx02d1 g7201__6877(.I0 (data_in[0]), .I1 (\top3_data_out2[1] [0]), .S
       (n_215), .Z (n_217));
  mx02d1 g7202__2900(.I0 (data_in[1]), .I1 (\top3_data_out2[1] [1]), .S
       (n_215), .Z (n_216));
  mx02d1 g7203__2391(.I0 (data_in[2]), .I1 (\top3_data_out2[1] [2]), .S
       (n_215), .Z (n_214));
  mx02d1 g7204__7675(.I0 (data_in[3]), .I1 (\top3_data_out2[1] [3]), .S
       (n_215), .Z (n_213));
  mx02d1 g7205__7118(.I0 (data_in[4]), .I1 (\top3_data_out2[1] [4]), .S
       (n_215), .Z (n_212));
  mx02d1 g7206__8757(.I0 (data_in[5]), .I1 (\top3_data_out2[1] [5]), .S
       (n_215), .Z (n_211));
  mx02d1 g7207__1786(.I0 (data_in[6]), .I1 (\top3_data_out2[1] [6]), .S
       (n_215), .Z (n_210));
  mx02d1 g7208__5953(.I0 (data_in[7]), .I1 (\top3_data_out2[1] [7]), .S
       (n_215), .Z (n_209));
  mx02d1 g7209__5703(.I0 (\top3_data_out2[6] [0]), .I1 (data_in[0]), .S
       (n_206), .Z (n_208));
  mx02d1 g7210__7114(.I0 (\top3_data_out2[6] [1]), .I1 (data_in[1]), .S
       (n_206), .Z (n_207));
  mx02d1 g7211__5266(.I0 (\top3_data_out2[6] [2]), .I1 (data_in[2]), .S
       (n_206), .Z (n_205));
  mx02d1 g7212__2250(.I0 (\top3_data_out2[6] [3]), .I1 (data_in[3]), .S
       (n_206), .Z (n_204));
  mx02d1 g7213__6083(.I0 (\top3_data_out2[6] [4]), .I1 (data_in[4]), .S
       (n_206), .Z (n_203));
  mx02d1 g7137__2703(.I0 (data_in[1]), .I1 (\top3_data_out2[2] [1]), .S
       (n_197), .Z (n_202));
  mx02d1 g7214__5795(.I0 (\top3_data_out2[6] [5]), .I1 (data_in[5]), .S
       (n_206), .Z (n_201));
  mx02d1 g7215__7344(.I0 (\top3_data_out2[6] [6]), .I1 (data_in[6]), .S
       (n_206), .Z (n_200));
  mx02d1 g7216__1840(.I0 (\top3_data_out2[6] [7]), .I1 (data_in[7]), .S
       (n_206), .Z (n_199));
  mx02d1 g7138__5019(.I0 (data_in[0]), .I1 (\top3_data_out2[2] [0]), .S
       (n_197), .Z (n_198));
  mx02d1 g7217__1857(.I0 (\top3_data_out2[12] [1]), .I1 (data_in[1]),
       .S (n_193), .Z (n_196));
  mx02d1 g7139__9906(.I0 (data_in[2]), .I1 (\top3_data_out2[2] [2]), .S
       (n_197), .Z (n_195));
  mx02d1 g7218__8780(.I0 (\top3_data_out2[12] [2]), .I1 (data_in[2]),
       .S (n_193), .Z (n_194));
  mx02d1 g7219__4296(.I0 (\top3_data_out2[12] [0]), .I1 (data_in[0]),
       .S (n_193), .Z (n_192));
  mx02d1 g7140__3772(.I0 (data_in[3]), .I1 (\top3_data_out2[2] [3]), .S
       (n_197), .Z (n_191));
  mx02d1 g7220__1474(.I0 (\top3_data_out2[12] [3]), .I1 (data_in[3]),
       .S (n_193), .Z (n_190));
  mx02d1 g7221__4547(.I0 (\top3_data_out2[12] [4]), .I1 (data_in[4]),
       .S (n_193), .Z (n_189));
  mx02d1 g7141__9682(.I0 (data_in[4]), .I1 (\top3_data_out2[2] [4]), .S
       (n_197), .Z (n_188));
  mx02d1 g7222__2683(.I0 (\top3_data_out2[12] [5]), .I1 (data_in[5]),
       .S (n_193), .Z (n_187));
  mx02d1 g7223__1309(.I0 (\top3_data_out2[12] [6]), .I1 (data_in[6]),
       .S (n_193), .Z (n_186));
  mx02d1 g7142__6877(.I0 (data_in[5]), .I1 (\top3_data_out2[2] [5]), .S
       (n_197), .Z (n_185));
  mx02d1 g7224__2900(.I0 (\top3_data_out2[12] [7]), .I1 (data_in[7]),
       .S (n_193), .Z (n_184));
  mx02d1 g7225__2391(.I0 (\top3_data_out2[14] [0]), .I1 (data_in[0]),
       .S (n_229), .Z (n_183));
  mx02d1 g7143__7675(.I0 (data_in[6]), .I1 (\top3_data_out2[2] [6]), .S
       (n_197), .Z (n_182));
  mx02d1 g7226__7118(.I0 (\top3_data_out2[14] [1]), .I1 (data_in[1]),
       .S (n_229), .Z (n_181));
  mx02d1 g7227__8757(.I0 (\top3_data_out2[14] [2]), .I1 (data_in[2]),
       .S (n_229), .Z (n_180));
  mx02d1 g7144__1786(.I0 (data_in[7]), .I1 (\top3_data_out2[2] [7]), .S
       (n_197), .Z (n_179));
  mx02d1 g7228__5953(.I0 (\top3_data_out2[14] [3]), .I1 (data_in[3]),
       .S (n_229), .Z (n_178));
  mx02d1 g7229__5703(.I0 (\top3_data_out2[14] [4]), .I1 (data_in[4]),
       .S (n_229), .Z (n_177));
  mx02d1 g7145__7114(.I0 (\top3_data_out2[8] [0]), .I1 (data_in[0]), .S
       (n_280), .Z (n_176));
  mx02d1 g7230__5266(.I0 (\top3_data_out2[14] [5]), .I1 (data_in[5]),
       .S (n_229), .Z (n_175));
  mx02d1 g7182__2250(.I0 (data_in[6]), .I1 (\top3_data_out2[9] [6]), .S
       (n_329), .Z (n_174));
  nr02d1 g7252__6083(.A1 (n_172), .A2 (wptr[3]), .ZN (n_309));
  decrq1 top4_fifo_underflow_reg(.CDN (rst_n), .CP (clk), .D (n_145),
       .ENN (n_142), .Q (fifo_underflow));
  decrq1 top4_fifo_overflow_reg(.CDN (rst_n), .CP (clk), .D (n_144),
       .ENN (n_139), .Q (fifo_overflow));
  oaim22d1 g7294__5795(.A1 (rptr[4]), .A2 (n_170), .B1 (rptr[4]), .B2
       (n_170), .ZN (n_171));
  oai211d1 g7293__7344(.A (n_17), .B (n_148), .C1 (n_5), .C2 (n_154),
       .ZN (n_169));
  oai21d1 g7302__1840(.A (n_153), .B1 (n_152), .B2 (n_151), .ZN
       (n_168));
  inv0d0 g7298(.I (n_172), .ZN (n_167));
  nr02d1 g7265__5019(.A1 (n_153), .A2 (n_166), .ZN (n_300));
  nr02d1 g7264__9906(.A1 (n_161), .A2 (n_166), .ZN (n_229));
  nr02d1 g7263__8780(.A1 (n_162), .A2 (n_166), .ZN (n_193));
  nd02d1 g7259__3772(.A1 (n_164), .A2 (n_165), .ZN (n_215));
  nd12d1 g7299__1474(.A1 (n_163), .A2 (wptr[2]), .ZN (n_172));
  nr02d1 g7269__4547(.A1 (n_162), .A2 (n_160), .ZN (n_280));
  nr02d1 g7262__9682(.A1 (n_161), .A2 (n_160), .ZN (n_224));
  nd12d1 g7301__2683(.A1 (n_163), .A2 (n_164), .ZN (n_249));
  nr02d1 g7268__1309(.A1 (n_162), .A2 (n_159), .ZN (n_268));
  nr02d1 g7261__6877(.A1 (n_161), .A2 (n_159), .ZN (n_206));
  nr02d1 g7305__2900(.A1 (n_163), .A2 (n_160), .ZN (n_259));
  nd12d1 g7260__2391(.A1 (n_161), .A2 (n_164), .ZN (n_197));
  inv0d0 g7286(.I (n_165), .ZN (n_153));
  oai211d1 g7303__7675(.A (n_20), .B (n_137), .C1 (n_21), .C2 (n_146),
       .ZN (n_156));
  mx02d1 g7304__7118(.I0 (rptr[2]), .I1 (n_1), .S (n_154), .Z (n_155));
  nd02d1 g7307__8757(.A1 (n_14), .A2 (n_154), .ZN (n_170));
  nd02d1 g7296__1786(.A1 (n_152), .A2 (n_150), .ZN (n_162));
  nd02d1 g7308__5953(.A1 (wptr[1]), .A2 (n_151), .ZN (n_163));
  nd02d1 g7297__5703(.A1 (wptr[1]), .A2 (n_150), .ZN (n_161));
  aor21d1 g7311__7114(.A (n_150), .B1 (wptr[0]), .B2 (n_140), .Z
       (n_149));
  nd02d0 g7310__5266(.A1 (n_15), .A2 (n_154), .ZN (n_148));
  oai22d1 g7312__2250(.A1 (rptr[0]), .A2 (n_146), .B1 (n_27), .B2
       (n_143), .ZN (n_147));
  an02d1 g7309__6083(.A1 (n_152), .A2 (n_151), .Z (n_165));
  nr02d0 g7313__2703(.A1 (n_136), .A2 (n_141), .ZN (n_145));
  nr02d0 g7314__5795(.A1 (n_143), .A2 (n_138), .ZN (n_144));
  an02d1 g7315__7344(.A1 (n_141), .A2 (n_140), .Z (n_142));
  an02d1 g7316__1840(.A1 (n_146), .A2 (n_138), .Z (n_139));
  nd02d0 g7317__5019(.A1 (rptr[1]), .A2 (n_146), .ZN (n_137));
  nr02d1 g7318__1857(.A1 (n_140), .A2 (wptr[0]), .ZN (n_150));
  nr02d1 g7319__9906(.A1 (n_140), .A2 (n_29), .ZN (n_151));
  nr02d1 g7320__8780(.A1 (n_146), .A2 (n_23), .ZN (n_154));
  inv0d0 g7321(.I (n_140), .ZN (n_136));
  inv0d0 g7322(.I (n_146), .ZN (n_143));
  nd12d1 g7323__4296(.A1 (fifo_full), .A2 (wr), .ZN (n_140));
  nd12d1 g7324__3772(.A1 (fifo_empty), .A2 (rd), .ZN (n_146));
  nd02d1 g7325__1474(.A1 (fifo_full), .A2 (wr), .ZN (n_138));
  nd02d1 g7326__4547(.A1 (fifo_empty), .A2 (rd), .ZN (n_141));
  nr02d1 g7327__9682(.A1 (n_123), .A2 (n_133), .ZN (fifo_full));
  nr02d1 g7328__2683(.A1 (n_18), .A2 (n_133), .ZN (fifo_empty));
  nd04d0 g7335__1309(.A1 (n_50), .A2 (n_117), .A3 (n_38), .A4 (n_65),
       .ZN (data_out[0]));
  nd04d0 g7331__6877(.A1 (n_42), .A2 (n_119), .A3 (n_32), .A4 (n_60),
       .ZN (data_out[6]));
  nd04d0 g7334__2900(.A1 (n_74), .A2 (n_120), .A3 (n_34), .A4 (n_57),
       .ZN (data_out[7]));
  nd04d0 g7330__2391(.A1 (n_85), .A2 (n_121), .A3 (n_84), .A4 (n_46),
       .ZN (data_out[2]));
  nd04d0 g7338__7675(.A1 (n_72), .A2 (n_115), .A3 (n_41), .A4 (n_63),
       .ZN (data_out[3]));
  nd04d0 g7336__7118(.A1 (n_69), .A2 (n_114), .A3 (n_36), .A4 (n_68),
       .ZN (data_out[4]));
  nd04d0 g7333__8757(.A1 (n_58), .A2 (n_118), .A3 (n_43), .A4 (n_54),
       .ZN (data_out[1]));
  nd04d0 g7337__1786(.A1 (n_82), .A2 (n_111), .A3 (n_71), .A4 (n_80),
       .ZN (data_out[5]));
  oai211d1 g7332__5953(.A (n_122), .B (n_26), .C1 (n_123), .C2 (n_25),
       .ZN (fifo_threshold));
  nd04d1 g7329__5703(.A1 (n_13), .A2 (n_122), .A3 (n_28), .A4 (n_102),
       .ZN (n_133));
  aoi21d1 g7340__7114(.A (n_110), .B1 (n_92), .B2
       (\top3_data_out2[6] [2]), .ZN (n_121));
  aoi21d1 g7342__5266(.A (n_106), .B1 (n_116), .B2
       (\top3_data_out2[7] [7]), .ZN (n_120));
  aoi21d1 g7343__2250(.A (n_109), .B1 (n_95), .B2
       (\top3_data_out2[15] [6]), .ZN (n_119));
  aoi21d1 g7346__6083(.A (n_105), .B1 (n_97), .B2
       (\top3_data_out2[13] [1]), .ZN (n_118));
  aoi21d1 g7345__2703(.A (n_104), .B1 (n_116), .B2
       (\top3_data_out2[7] [0]), .ZN (n_117));
  aoi21d1 g7344__5795(.A (n_107), .B1 (n_116), .B2
       (\top3_data_out2[7] [3]), .ZN (n_115));
  aoi21d1 g7347__7344(.A (n_108), .B1 (n_93), .B2
       (\top3_data_out2[4] [4]), .ZN (n_114));
  aoim22d1 g7339__1840(.A1 (n_113), .A2 (n_112), .B1 (n_113), .B2
       (n_112), .Z (n_122));
  aoi21d1 g7341__5019(.A (n_103), .B1 (n_100), .B2
       (\top3_data_out2[11] [5]), .ZN (n_111));
  nd04d0 g7348__1857(.A1 (n_78), .A2 (n_101), .A3 (n_44), .A4 (n_86),
       .ZN (n_110));
  nd04d0 g7349__9906(.A1 (n_53), .A2 (n_48), .A3 (n_91), .A4 (n_51),
       .ZN (n_109));
  nd04d0 g7352__8780(.A1 (n_61), .A2 (n_88), .A3 (n_33), .A4 (n_52),
       .ZN (n_108));
  nd04d0 g7355__4296(.A1 (n_66), .A2 (n_99), .A3 (n_37), .A4 (n_55),
       .ZN (n_107));
  nd04d0 g7354__3772(.A1 (n_64), .A2 (n_96), .A3 (n_39), .A4 (n_67),
       .ZN (n_106));
  nd04d0 g7353__1474(.A1 (n_49), .A2 (n_31), .A3 (n_94), .A4 (n_56),
       .ZN (n_105));
  nd04d0 g7356__4547(.A1 (n_35), .A2 (n_90), .A3 (n_40), .A4 (n_62),
       .ZN (n_104));
  nd04d0 g7350__9682(.A1 (n_87), .A2 (n_77), .A3 (n_45), .A4 (n_75),
       .ZN (n_103));
  oan211d1 g7351__2683(.A (n_12), .B (n_102), .C1 (n_30), .C2 (n_24),
       .ZN (n_113));
  aoi222d1 g7357__1309(.A1 (\top3_data_out2[5] [2]), .A2 (n_98), .B1
       (n_81), .B2 (\top3_data_out2[14] [2]), .C1
       (\top3_data_out2[11] [2]), .C2 (n_100), .ZN (n_101));
  aoi222d1 g7358__6877(.A1 (\top3_data_out2[5] [3]), .A2 (n_98), .B1
       (n_89), .B2 (\top3_data_out2[10] [3]), .C1
       (\top3_data_out2[13] [3]), .C2 (n_97), .ZN (n_99));
  aoi222d1 g7359__2900(.A1 (\top3_data_out2[5] [7]), .A2 (n_98), .B1
       (n_70), .B2 (\top3_data_out2[12] [7]), .C1
       (\top3_data_out2[15] [7]), .C2 (n_95), .ZN (n_96));
  aoi222d1 g7363__2391(.A1 (\top3_data_out2[4] [1]), .A2 (n_93), .B1
       (n_92), .B2 (\top3_data_out2[6] [1]), .C1 (\top3_data_out2[5]
       [1]), .C2 (n_98), .ZN (n_94));
  aoi222d1 g7362__7675(.A1 (\top3_data_out2[5] [6]), .A2 (n_98), .B1
       (n_93), .B2 (\top3_data_out2[4] [6]), .C1 (\top3_data_out2[6]
       [6]), .C2 (n_92), .ZN (n_91));
  aoi222d1 g7361__7118(.A1 (\top3_data_out2[5] [0]), .A2 (n_98), .B1
       (n_89), .B2 (\top3_data_out2[10] [0]), .C1
       (\top3_data_out2[13] [0]), .C2 (n_97), .ZN (n_90));
  aoi222d1 g7364__8757(.A1 (\top3_data_out2[5] [4]), .A2 (n_98), .B1
       (n_89), .B2 (\top3_data_out2[10] [4]), .C1
       (\top3_data_out2[15] [4]), .C2 (n_95), .ZN (n_88));
  aoi22d1 g7376__1786(.A1 (n_83), .A2 (\top3_data_out2[0] [5]), .B1
       (n_98), .B2 (\top3_data_out2[5] [5]), .ZN (n_87));
  aoi22d1 g7365__5953(.A1 (n_79), .A2 (\top3_data_out2[8] [2]), .B1
       (n_95), .B2 (\top3_data_out2[15] [2]), .ZN (n_86));
  aoi22d1 g7367__5703(.A1 (n_76), .A2 (\top3_data_out2[3] [2]), .B1
       (n_116), .B2 (\top3_data_out2[7] [2]), .ZN (n_85));
  aoi22d1 g7368__7114(.A1 (n_83), .A2 (\top3_data_out2[0] [2]), .B1
       (n_47), .B2 (\top3_data_out2[1] [2]), .ZN (n_84));
  aoi22d1 g7370__5266(.A1 (n_89), .A2 (\top3_data_out2[10] [5]), .B1
       (n_81), .B2 (\top3_data_out2[14] [5]), .ZN (n_82));
  aoi22d1 g7372__2250(.A1 (n_79), .A2 (\top3_data_out2[8] [5]), .B1
       (n_95), .B2 (\top3_data_out2[15] [5]), .ZN (n_80));
  aoi22d1 g7373__6083(.A1 (n_89), .A2 (\top3_data_out2[10] [2]), .B1
       (n_97), .B2 (\top3_data_out2[13] [2]), .ZN (n_78));
  aoi222d1 g7360__2703(.A1 (\top3_data_out2[2] [5]), .A2 (n_73), .B1
       (n_92), .B2 (\top3_data_out2[6] [5]), .C1 (\top3_data_out2[3]
       [5]), .C2 (n_76), .ZN (n_77));
  aoi22d1 g7378__5795(.A1 (n_93), .A2 (\top3_data_out2[4] [5]), .B1
       (n_116), .B2 (\top3_data_out2[7] [5]), .ZN (n_75));
  aoi22d1 g7379__7344(.A1 (n_83), .A2 (\top3_data_out2[0] [7]), .B1
       (n_73), .B2 (\top3_data_out2[2] [7]), .ZN (n_74));
  aoi22d1 g7383__1840(.A1 (n_83), .A2 (\top3_data_out2[0] [3]), .B1
       (n_76), .B2 (\top3_data_out2[3] [3]), .ZN (n_72));
  aoi22d1 g7384__5019(.A1 (n_70), .A2 (\top3_data_out2[12] [5]), .B1
       (n_97), .B2 (\top3_data_out2[13] [5]), .ZN (n_71));
  aoi22d1 g7387__1857(.A1 (n_73), .A2 (\top3_data_out2[2] [4]), .B1
       (n_92), .B2 (\top3_data_out2[6] [4]), .ZN (n_69));
  aoi22d1 g7388__9906(.A1 (n_83), .A2 (\top3_data_out2[0] [4]), .B1
       (n_116), .B2 (\top3_data_out2[7] [4]), .ZN (n_68));
  aoi22d1 g7390__8780(.A1 (n_59), .A2 (\top3_data_out2[9] [7]), .B1
       (n_81), .B2 (\top3_data_out2[14] [7]), .ZN (n_67));
  aoi22d1 g7414__4296(.A1 (n_100), .A2 (\top3_data_out2[11] [3]), .B1
       (n_81), .B2 (\top3_data_out2[14] [3]), .ZN (n_66));
  aoi22d1 g7394__3772(.A1 (n_93), .A2 (\top3_data_out2[4] [0]), .B1
       (n_92), .B2 (\top3_data_out2[6] [0]), .ZN (n_65));
  aoi22d1 g7395__1474(.A1 (n_79), .A2 (\top3_data_out2[8] [7]), .B1
       (n_97), .B2 (\top3_data_out2[13] [7]), .ZN (n_64));
  aoi22d1 g7396__4547(.A1 (n_93), .A2 (\top3_data_out2[4] [3]), .B1
       (n_92), .B2 (\top3_data_out2[6] [3]), .ZN (n_63));
  aoi22d1 g7397__9682(.A1 (n_81), .A2 (\top3_data_out2[14] [0]), .B1
       (n_95), .B2 (\top3_data_out2[15] [0]), .ZN (n_62));
  aoi22d1 g7398__2683(.A1 (n_100), .A2 (\top3_data_out2[11] [4]), .B1
       (n_81), .B2 (\top3_data_out2[14] [4]), .ZN (n_61));
  aoi22d1 g7402__1309(.A1 (n_59), .A2 (\top3_data_out2[9] [6]), .B1
       (n_81), .B2 (\top3_data_out2[14] [6]), .ZN (n_60));
  aoi22d1 g7403__6877(.A1 (n_70), .A2 (\top3_data_out2[12] [1]), .B1
       (n_95), .B2 (\top3_data_out2[15] [1]), .ZN (n_58));
  aoi22d1 g7404__2900(.A1 (n_93), .A2 (\top3_data_out2[4] [7]), .B1
       (n_92), .B2 (\top3_data_out2[6] [7]), .ZN (n_57));
  aoi22d1 g7406__2391(.A1 (n_83), .A2 (\top3_data_out2[0] [1]), .B1
       (n_116), .B2 (\top3_data_out2[7] [1]), .ZN (n_56));
  aoi22d1 g7408__7675(.A1 (n_70), .A2 (\top3_data_out2[12] [3]), .B1
       (n_95), .B2 (\top3_data_out2[15] [3]), .ZN (n_55));
  aoi22d1 g7409__7118(.A1 (n_100), .A2 (\top3_data_out2[11] [1]), .B1
       (n_81), .B2 (\top3_data_out2[14] [1]), .ZN (n_54));
  aoi22d1 g7410__8757(.A1 (n_73), .A2 (\top3_data_out2[2] [6]), .B1
       (n_97), .B2 (\top3_data_out2[13] [6]), .ZN (n_53));
  aoi22d1 g7411__1786(.A1 (n_79), .A2 (\top3_data_out2[8] [4]), .B1
       (n_97), .B2 (\top3_data_out2[13] [4]), .ZN (n_52));
  aoi22d1 g7413__5953(.A1 (n_83), .A2 (\top3_data_out2[0] [6]), .B1
       (n_116), .B2 (\top3_data_out2[7] [6]), .ZN (n_51));
  aoi22d1 g7393__5703(.A1 (n_83), .A2 (\top3_data_out2[0] [0]), .B1
       (n_73), .B2 (\top3_data_out2[2] [0]), .ZN (n_50));
  aoi22d1 g7385__7114(.A1 (n_73), .A2 (\top3_data_out2[2] [1]), .B1
       (n_89), .B2 (\top3_data_out2[10] [1]), .ZN (n_49));
  aoi22d1 g7369__5266(.A1 (n_47), .A2 (\top3_data_out2[1] [6]), .B1
       (n_76), .B2 (\top3_data_out2[3] [6]), .ZN (n_48));
  aoi22d1 g7371__2250(.A1 (n_73), .A2 (\top3_data_out2[2] [2]), .B1
       (n_93), .B2 (\top3_data_out2[4] [2]), .ZN (n_46));
  aoi22d1 g7374__6083(.A1 (n_47), .A2 (\top3_data_out2[1] [5]), .B1
       (n_59), .B2 (\top3_data_out2[9] [5]), .ZN (n_45));
  aoi22d1 g7375__2703(.A1 (n_70), .A2 (\top3_data_out2[12] [2]), .B1
       (n_59), .B2 (\top3_data_out2[9] [2]), .ZN (n_44));
  aoi22d1 g7380__5795(.A1 (n_79), .A2 (\top3_data_out2[8] [1]), .B1
       (n_59), .B2 (\top3_data_out2[9] [1]), .ZN (n_43));
  aoi22d1 g7381__7344(.A1 (n_79), .A2 (\top3_data_out2[8] [6]), .B1
       (n_89), .B2 (\top3_data_out2[10] [6]), .ZN (n_42));
  aoi22d1 g7382__1840(.A1 (n_47), .A2 (\top3_data_out2[1] [3]), .B1
       (n_73), .B2 (\top3_data_out2[2] [3]), .ZN (n_41));
  aoi22d1 g7401__5019(.A1 (n_79), .A2 (\top3_data_out2[8] [0]), .B1
       (n_100), .B2 (\top3_data_out2[11] [0]), .ZN (n_40));
  aoi22d1 g7412__1857(.A1 (n_89), .A2 (\top3_data_out2[10] [7]), .B1
       (n_100), .B2 (\top3_data_out2[11] [7]), .ZN (n_39));
  aoi22d1 g7389__9906(.A1 (n_47), .A2 (\top3_data_out2[1] [0]), .B1
       (n_76), .B2 (\top3_data_out2[3] [0]), .ZN (n_38));
  aoi22d1 g7391__8780(.A1 (n_79), .A2 (\top3_data_out2[8] [3]), .B1
       (n_59), .B2 (\top3_data_out2[9] [3]), .ZN (n_37));
  aoi22d1 g7392__4296(.A1 (n_47), .A2 (\top3_data_out2[1] [4]), .B1
       (n_76), .B2 (\top3_data_out2[3] [4]), .ZN (n_36));
  aoi22d1 g7399__3772(.A1 (n_70), .A2 (\top3_data_out2[12] [0]), .B1
       (n_59), .B2 (\top3_data_out2[9] [0]), .ZN (n_35));
  aoi22d1 g7400__1474(.A1 (n_47), .A2 (\top3_data_out2[1] [7]), .B1
       (n_76), .B2 (\top3_data_out2[3] [7]), .ZN (n_34));
  aoi22d1 g7405__4547(.A1 (n_70), .A2 (\top3_data_out2[12] [4]), .B1
       (n_59), .B2 (\top3_data_out2[9] [4]), .ZN (n_33));
  aoi22d1 g7407__9682(.A1 (n_70), .A2 (\top3_data_out2[12] [6]), .B1
       (n_100), .B2 (\top3_data_out2[11] [6]), .ZN (n_32));
  aoi22d1 g7386__2683(.A1 (n_47), .A2 (\top3_data_out2[1] [1]), .B1
       (n_76), .B2 (\top3_data_out2[3] [1]), .ZN (n_31));
  oai22d1 g7366__1309(.A1 (n_8), .A2 (n_152), .B1 (rptr[1]), .B2
       (n_29), .ZN (n_30));
  aoi221d1 g7415__6877(.A (n_11), .B1 (wptr[0]), .B2 (n_27), .C1
       (n_29), .C2 (rptr[0]), .ZN (n_28));
  nd02d0 g7377__2900(.A1 (n_123), .A2 (n_25), .ZN (n_26));
  an02d1 g7420__2391(.A1 (n_9), .A2 (n_24), .Z (n_83));
  nr02d0 g7421__7675(.A1 (n_22), .A2 (n_23), .ZN (n_95));
  nr02d0 g7434__7118(.A1 (n_22), .A2 (n_21), .ZN (n_97));
  nr02d0 g7432__8757(.A1 (n_20), .A2 (n_19), .ZN (n_92));
  nr02d0 g7430__1786(.A1 (n_19), .A2 (n_21), .ZN (n_98));
  nr02d0 g7423__5953(.A1 (n_22), .A2 (n_20), .ZN (n_81));
  nr02d0 g7435__5703(.A1 (n_23), .A2 (n_19), .ZN (n_116));
  inv0d0 g7426(.I (n_123), .ZN (n_18));
  nr02d0 g7431__7114(.A1 (n_17), .A2 (n_21), .ZN (n_59));
  nr02d0 g7417__5266(.A1 (n_16), .A2 (n_21), .ZN (n_47));
  nr02d0 g7418__2250(.A1 (n_16), .A2 (n_23), .ZN (n_76));
  nr02d0 g7419__6083(.A1 (n_16), .A2 (n_20), .ZN (n_73));
  an02d1 g7425__2703(.A1 (n_15), .A2 (n_24), .Z (n_93));
  nr02d0 g7424__5795(.A1 (n_17), .A2 (n_3), .ZN (n_79));
  an02d1 g7422__7344(.A1 (n_14), .A2 (n_24), .Z (n_70));
  nr02d0 g7433__1840(.A1 (n_17), .A2 (n_20), .ZN (n_89));
  nr02d0 g7436__5019(.A1 (n_17), .A2 (n_23), .ZN (n_100));
  inv0d0 g7447(.I (n_12), .ZN (n_13));
  oai22d1 g7427__1857(.A1 (rptr[1]), .A2 (n_152), .B1 (wptr[1]), .B2
       (n_0), .ZN (n_11));
  inv0d0 g7438(.I (n_14), .ZN (n_22));
  inv0d0 g7450(.I (n_15), .ZN (n_19));
  inv0d0 g7437(.I (n_16), .ZN (n_9));
  nr02d1 g7416__9906(.A1 (wptr[0]), .A2 (n_23), .ZN (n_8));
  oai22d1 g7428__8780(.A1 (rptr[3]), .A2 (wptr[3]), .B1 (n_6), .B2
       (n_5), .ZN (n_112));
  aoim22d1 g7429__4296(.A1 (rptr[4]), .A2 (n_4), .B1 (rptr[4]), .B2
       (n_4), .Z (n_123));
  inv0d0 g7439(.I (n_24), .ZN (n_3));
  nr02d0 g7440__3772(.A1 (wptr[3]), .A2 (n_5), .ZN (n_25));
  nr02d0 g7452__1474(.A1 (n_2), .A2 (rptr[2]), .ZN (n_12));
  nd02d1 g7451__4547(.A1 (rptr[2]), .A2 (n_2), .ZN (n_102));
  nr02d1 g7444__9682(.A1 (n_1), .A2 (n_5), .ZN (n_14));
  nd02d0 g7442__2683(.A1 (n_5), .A2 (n_1), .ZN (n_16));
  nd02d1 g7453__1309(.A1 (n_6), .A2 (wptr[2]), .ZN (n_159));
  nr02d1 g7456__6877(.A1 (n_1), .A2 (rptr[3]), .ZN (n_15));
  nd02d1 g7454__2900(.A1 (wptr[3]), .A2 (n_2), .ZN (n_160));
  nd02d1 g7457__2391(.A1 (rptr[0]), .A2 (n_0), .ZN (n_21));
  nd02d1 g7458__7675(.A1 (rptr[1]), .A2 (n_27), .ZN (n_20));
  nd02d1 g7455__7118(.A1 (rptr[3]), .A2 (n_1), .ZN (n_17));
  nr02d1 g7443__8757(.A1 (wptr[2]), .A2 (wptr[3]), .ZN (n_164));
  nd02d1 g7446__1786(.A1 (rptr[1]), .A2 (rptr[0]), .ZN (n_23));
  nd02d1 g7441__5953(.A1 (wptr[3]), .A2 (wptr[2]), .ZN (n_166));
  nr02d1 g7445__5703(.A1 (rptr[0]), .A2 (rptr[1]), .ZN (n_24));
  dfcrb1 \top2_rptr_reg[0] (.CDN (rst_n), .CP (clk), .D (n_147), .Q
       (rptr[0]), .QN (n_27));
  dfcrb1 \top1_wptr_reg[0] (.CDN (rst_n), .CP (clk), .D (n_149), .Q
       (wptr[0]), .QN (n_29));
  dfcrb1 \top2_rptr_reg[3] (.CDN (rst_n), .CP (clk), .D (n_169), .Q
       (rptr[3]), .QN (n_5));
  dfcrb1 \top1_wptr_reg[1] (.CDN (rst_n), .CP (clk), .D (n_168), .Q
       (wptr[1]), .QN (n_152));
  dfcrb1 \top2_rptr_reg[1] (.CDN (rst_n), .CP (clk), .D (n_156), .Q
       (rptr[1]), .QN (n_0));
  dfcrb1 \top1_wptr_reg[4] (.CDN (rst_n), .CP (clk), .D (n_313), .Q
       (wptr[4]), .QN (n_4));
  dfcrb1 \top1_wptr_reg[3] (.CDN (rst_n), .CP (clk), .D (n_322), .Q
       (wptr[3]), .QN (n_6));
  dfcrb1 \top1_wptr_reg[2] (.CDN (rst_n), .CP (clk), .D (n_233), .Q
       (wptr[2]), .QN (n_2));
  dfcrb1 \top2_rptr_reg[2] (.CDN (rst_n), .CP (clk), .D (n_155), .Q
       (rptr[2]), .QN (n_1));
  nd12d1 g2(.A1 (n_162), .A2 (n_164), .ZN (n_327));
  nd12d1 g7626(.A1 (n_159), .A2 (n_165), .ZN (n_328));
  nd12d1 g7627(.A1 (n_160), .A2 (n_165), .ZN (n_329));

/////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////
/// clock and reset pin instantation
pc3d01 Frst_n(.PAD(rst_n),.CIN(rst_n));
pc3c01 Fclk(.CCLK(clk),.CP(clk1));
//input data line
pc3d01 dataIn7(.PAD(data_in[7]),.CIN(data_in[7]));
pc3d01 dataIn6(.PAD(data_in[6]),.CIN(data_in[6]));
pc3d01 dataIn5(.PAD(data_in[5]),.CIN(data_in[5]));
pc3d01 dataIn4(.PAD(data_in[4]),.CIN(data_in[4]));
pc3d01 dataIn3(.PAD(data_in[3]),.CIN(data_in[3]));
pc3d01 dataIn2(.PAD(data_in[2]),.CIN(data_in[2]));
pc3d01 dataIn1(.PAD(data_in[1]),.CIN(data_in[1]));
pc3d01 dataIn0(.PAD(data_in[0]),.CIN(data_in[0]));
//output data line
pc3d01 dataOut7(.PAD(data_out[7]),.CIN(data_out[7]));
pc3d01 dataOut6(.PAD(data_out[6]),.CIN(data_out[6]));
pc3d01 dataOut5(.PAD(data_out[5]),.CIN(data_out[5]));
pc3d01 dataOut4(.PAD(data_out[4]),.CIN(data_out[4]));
pc3d01 dataOut3(.PAD(data_out[3]),.CIN(data_out[3]));
pc3d01 dataOut2(.PAD(data_out[2]),.CIN(data_out[2]));
pc3d01 dataOut1(.PAD(data_out[1]),.CIN(data_out[1]));
pc3d01 dataOut0(.PAD(data_out[0]),.CIN(data_out[0]));
//control line
pc3d01 Fwr(.PAD(wr),.CIN(wr));
pc3d01 Frd(.PAD(rd),.CIN(rd));
//status signal
pc3d01 Ffifo_full(.PAD(fifo_full),.CIN(fifo_full));
pc3d01 Ffifo_empty(.PAD(fifo_empty),.CIN(fifo_empty));
pc3d01 Ffifo_threshold(.PAD(fifo_threshold),.CIN(fifo_threshold));
pc3d01 Ffifo_overflow(.PAD(fifo_overflow),.CIN(fifo_overflow));
pc3d01 Ffifo_underflow(.PAD(fifo_underflow),.CIN(fifo_underflow));
endmodule

